M48
; DRILL file {KiCad 8.0.4} date 2024-10-15T03:41:10-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-15T03:41:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X4.2815Y-2.811
X4.2815Y-4.5039
X7.6673Y-2.811
X7.6673Y-4.5039
M30
